FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 300

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1


CMD ["streamlit", "run", "🏠_Homepage.py"]