FROM python:3.10-slim

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3001

HEALTHCHECK CMD curl --fail http://localhost:3001/health || exit 1


CMD ["python", "back.py"]